# Generated by Django 5.2.6 on 2025-09-17 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='card_id',
            new_name='cart_id',
        ),
    ]
